// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/autochip-home/CurrentHome.tsx": () => import("../components/mockups/autochip-home/CurrentHome.tsx"),
  "./components/mockups/autochip-home/ProgrammerPicker.tsx": () => import("../components/mockups/autochip-home/ProgrammerPicker.tsx")
};
